services:
  - name: connexabot-backend
    type: web
    instance_type: nano
    regions:
      - fra
    ports:
      - port: 5000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: AUTH_DIR
        value: /data/auth
      - key: MEDIA_DIR
        value: /data/media
      - key: CHAT_HISTORY_DIR
        value: /data/chat_history
    volumes:
      - scope: region
        path: /data
        name: app-data
    build:
      builder: dockerfile
      dockerfile: Dockerfile
    routes:
      - path: /
        port: 5000
    health_checks:
      - path: /health
        port: 5000
        protocol: http
        interval: 30s
        timeout: 5s
        grace_period: 30s
